#!/bin/bash

topdir=$(readlink -f $0 | xargs dirname | xargs dirname)

/bin/ls  ../sourcedata/dbic-BIDS/Haxby/Sam/*/sourcedata/sub-*/ses-*/anat/*T1w.dicom.tgz | grep -v scout | xargs python convert_to_bids.py

